# Generated by Django 5.1.15 on 2026-06-12 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of the file bytes; used for duplicate detection.', max_length=64)),
                ('ai_extracted', models.JSONField(blank=True, default=dict)),
                ('ai_vendor', models.CharField(blank=True, max_length=200)),
                ('ai_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_date', models.DateField(blank=True, null=True)),
                ('ai_currency', models.CharField(blank=True, max_length=8)),
                ('ai_is_receipt', models.BooleanField(default=True)),
                ('ai_provider', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AI_FLAGGED', 'Flagged by AI'), ('MANAGER_REVIEW', 'Awaiting Manager'), ('ACCOUNTS_REVIEW', 'Awaiting Accounts'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_flags', models.JSONField(blank=True, default=list)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='accounts.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AI_VALIDATED', 'AI validated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Marked paid')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='claims.expenseclaim')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TAXI', 'Taxi / Transport'), ('FOOD', 'Food / Meals'), ('SUPPLIES', 'Office Supplies'), ('FUEL', 'Fuel'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_flags', models.JSONField(blank=True, default=list)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='claims.expenseclaim')),
                ('receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='claims.receipt')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
