# Generated by Django 5.1.15 on 2026-06-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AI_FLAGGED', 'Flagged by AI'), ('MANAGER_REVIEW', 'Awaiting Manager'), ('FINANCE_REVIEW', 'Awaiting Finance Manager'), ('ACCOUNTS_REVIEW', 'Awaiting Accounts'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
