# Generated by Django 5.1.15 on 2026-06-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_expenseclaim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimitem',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
