# Generated by Django 5.1.15 on 2026-06-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Branch Manager'), ('FINANCE', 'Finance Manager'), ('ACCOUNTS', 'Accounts / Finance'), ('ADMIN', 'Administrator')], default='EMPLOYEE', max_length=20),
        ),
    ]
